//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doosan.TriangleWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TriangleWS.ITriangleAPI")]
    public interface ITriangleAPI {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetPO", ReplyAction="http://tempuri.org/ITriangleAPI/GetPOResponse")]
        System.Data.DataSet GetPO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetPO", ReplyAction="http://tempuri.org/ITriangleAPI/GetPOResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetAppPO", ReplyAction="http://tempuri.org/ITriangleAPI/GetAppPOResponse")]
        System.Data.DataSet GetAppPO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetAppPO", ReplyAction="http://tempuri.org/ITriangleAPI/GetAppPOResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAppPOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetDecPO", ReplyAction="http://tempuri.org/ITriangleAPI/GetDecPOResponse")]
        System.Data.DataSet GetDecPO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetDecPO", ReplyAction="http://tempuri.org/ITriangleAPI/GetDecPOResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDecPOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetPendPO", ReplyAction="http://tempuri.org/ITriangleAPI/GetPendPOResponse")]
        System.Data.DataSet GetPendPO();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetPendPO", ReplyAction="http://tempuri.org/ITriangleAPI/GetPendPOResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPendPOAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetPODetails", ReplyAction="http://tempuri.org/ITriangleAPI/GetPODetailsResponse")]
        System.Data.DataSet GetPODetails(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetPODetails", ReplyAction="http://tempuri.org/ITriangleAPI/GetPODetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPODetailsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/SuppApprove", ReplyAction="http://tempuri.org/ITriangleAPI/SuppApproveResponse")]
        System.Data.DataSet SuppApprove(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/SuppApprove", ReplyAction="http://tempuri.org/ITriangleAPI/SuppApproveResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SuppApproveAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/SuppDeclined", ReplyAction="http://tempuri.org/ITriangleAPI/SuppDeclinedResponse")]
        System.Data.DataSet SuppDeclined(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/SuppDeclined", ReplyAction="http://tempuri.org/ITriangleAPI/SuppDeclinedResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SuppDeclinedAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetPOProducts", ReplyAction="http://tempuri.org/ITriangleAPI/GetPOProductsResponse")]
        System.Data.DataSet GetPOProducts(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetPOProducts", ReplyAction="http://tempuri.org/ITriangleAPI/GetPOProductsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPOProductsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetPayment", ReplyAction="http://tempuri.org/ITriangleAPI/GetPaymentResponse")]
        System.Data.DataSet GetPayment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetPayment", ReplyAction="http://tempuri.org/ITriangleAPI/GetPaymentResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPaymentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetDetails", ReplyAction="http://tempuri.org/ITriangleAPI/GetDetailsResponse")]
        System.Data.DataSet GetDetails(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/GetDetails", ReplyAction="http://tempuri.org/ITriangleAPI/GetDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDetailsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/updateStatus", ReplyAction="http://tempuri.org/ITriangleAPI/updateStatusResponse")]
        void updateStatus(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/updateStatus", ReplyAction="http://tempuri.org/ITriangleAPI/updateStatusResponse")]
        System.Threading.Tasks.Task updateStatusAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/updateStatusDecline", ReplyAction="http://tempuri.org/ITriangleAPI/updateStatusDeclineResponse")]
        void updateStatusDecline(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/updateStatusDecline", ReplyAction="http://tempuri.org/ITriangleAPI/updateStatusDeclineResponse")]
        System.Threading.Tasks.Task updateStatusDeclineAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/Getallinvoice", ReplyAction="http://tempuri.org/ITriangleAPI/GetallinvoiceResponse")]
        System.Data.DataSet Getallinvoice();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITriangleAPI/Getallinvoice", ReplyAction="http://tempuri.org/ITriangleAPI/GetallinvoiceResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetallinvoiceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITriangleAPIChannel : Doosan.TriangleWS.ITriangleAPI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TriangleAPIClient : System.ServiceModel.ClientBase<Doosan.TriangleWS.ITriangleAPI>, Doosan.TriangleWS.ITriangleAPI {
        
        public TriangleAPIClient() {
        }
        
        public TriangleAPIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TriangleAPIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TriangleAPIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TriangleAPIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetPO() {
            return base.Channel.GetPO();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPOAsync() {
            return base.Channel.GetPOAsync();
        }
        
        public System.Data.DataSet GetAppPO() {
            return base.Channel.GetAppPO();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAppPOAsync() {
            return base.Channel.GetAppPOAsync();
        }
        
        public System.Data.DataSet GetDecPO() {
            return base.Channel.GetDecPO();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDecPOAsync() {
            return base.Channel.GetDecPOAsync();
        }
        
        public System.Data.DataSet GetPendPO() {
            return base.Channel.GetPendPO();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPendPOAsync() {
            return base.Channel.GetPendPOAsync();
        }
        
        public System.Data.DataSet GetPODetails(int id) {
            return base.Channel.GetPODetails(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPODetailsAsync(int id) {
            return base.Channel.GetPODetailsAsync(id);
        }
        
        public System.Data.DataSet SuppApprove(int id) {
            return base.Channel.SuppApprove(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SuppApproveAsync(int id) {
            return base.Channel.SuppApproveAsync(id);
        }
        
        public System.Data.DataSet SuppDeclined(int id) {
            return base.Channel.SuppDeclined(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SuppDeclinedAsync(int id) {
            return base.Channel.SuppDeclinedAsync(id);
        }
        
        public System.Data.DataSet GetPOProducts(int id) {
            return base.Channel.GetPOProducts(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPOProductsAsync(int id) {
            return base.Channel.GetPOProductsAsync(id);
        }
        
        public System.Data.DataSet GetPayment() {
            return base.Channel.GetPayment();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPaymentAsync() {
            return base.Channel.GetPaymentAsync();
        }
        
        public System.Data.DataSet GetDetails(int id) {
            return base.Channel.GetDetails(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDetailsAsync(int id) {
            return base.Channel.GetDetailsAsync(id);
        }
        
        public void updateStatus(int id) {
            base.Channel.updateStatus(id);
        }
        
        public System.Threading.Tasks.Task updateStatusAsync(int id) {
            return base.Channel.updateStatusAsync(id);
        }
        
        public void updateStatusDecline(int id) {
            base.Channel.updateStatusDecline(id);
        }
        
        public System.Threading.Tasks.Task updateStatusDeclineAsync(int id) {
            return base.Channel.updateStatusDeclineAsync(id);
        }
        
        public System.Data.DataSet Getallinvoice() {
            return base.Channel.Getallinvoice();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetallinvoiceAsync() {
            return base.Channel.GetallinvoiceAsync();
        }
    }
}
